### ISSUE TITLE
Clock frequency division test module

### ISSUE THREAD

**Issue by KalyanOntipuli** [Yaozhtj/sdcard_digital_recognition#2]
In Clock frequency division test module clk wiz_0 _test  instance name is used .But  clk_wiz_0. is not their in project 
![Capture1](https://user-images.githubusercontent.com/126324034/224646385-63b83e56-ca1d-4058-8a2d-3c03740cd824.JPG)
 In code we mentioned it as clk_div.

**Comment by edw4rdyao** [comment]
@kalyanontipuli sorry, i can not understand your issue, could you please describe it more clearly? :)

**Comment by edw4rdyao** [comment]
@kalyanontipuli the `clk wiz_0` module is in IP Catalog `Clocking Wizard (PLL)` https://github.com/edw4rdyao/sdcard_digital_recognition/issues/1
